PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX sin: <http://www.exemple.com/sin#> .
PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#> .

# Here we assume there is only one need defined. Else, each Tag, Question and Labeling should be linked with the InformationNeed.

CONSTRUCT {
	?kg prov:wasGeneratedBy <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_leaf_tags.rq#activity> ;
		dqv:hasQualityMeasurement [
			a dqv:QualityMeasurement ;
			rdfs:label ?label ;
			dqv:isMeasurementOf ?tag ;
			dqv:value ?agg
		] .
	<https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_leaf_tags.rq#activity> prov:used <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_leaf_tags.rq#activity> ;
		prov:wasAssociatedWith <https://orcid.org/0000-0001-6907-0136> .
} WHERE {
	{ SELECT ?tag ?taglab ?kg (SUM(?val * ?w) / SUM(?w) AS ?agg) WHERE {
		{ SELECT DISTINCT ?tag ?taglab ?kg ?metric ?w (xsd:decimal(?value) AS ?val) WHERE {
			?kg prov:wasDerivedFrom ?kge ;
				dqv:hasQualityMeasurement ?measurement .
			?measurement dqv:isMeasurementOf ?metric ;
				dqv:value ?value .
			?question sin:isImplementedBy ?metric .
			?tagging sin:questionTagged ?question ;
				sin:tagWith ?tag ;
				sin:weight ?w .
			?tag rdfs:label ?taglab
		}  }
	} GROUP BY ?kg ?tag }
	BIND ( CONCAT(?taglab, " measurement" )  AS ?label )
}
