PREFIX prov: <http://www.w3.org/ns/prov#>
PREFIX dqv: <http://www.w3.org/ns/dqv#>
PREFIX sin: <http://www.exemple.com/sin#> .

CONSTRUCT {
	?kg prov:wasGeneratedBy <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_creator_who.rq#activity> ;
		dqv:hasQualityMeasurement [
			a dqv:QualityMeasurement ;
			rdfs:label "Creator contributor measurement" ;
			dqv:computedOn ?endpointDescription ;
			dqv:isMeasurementOf <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_creator_who.rq>;
			dqv:value ?val_contr ;
			prov:generatedAtTime $dateLiteral
		] .
	<https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_creator_who.rq> a dqv:Metric ;
		rdfs:comment "Who are the creators of the KG and their role in this process? For all creators, indicates whether they are a person or an organization, provide information to identify them (name and point of contact such as email, or phone number, or address, or homepage), provide their qualifications, provide all characteristics which could have an influence on the KG." ;
    rdfs:label "Creator contributor" .
	<https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_creator_who.rq#activity> prov:used <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/queries/q_measure_creator_who.rq#activity> ;
		prov:wasAssociatedWith <https://orcid.org/0000-0001-6907-0136> .
} WHERE {
	# Main
	?kg prov:wasDerivedFrom ?kge ;
		dqv:hasQualityMeasurement ?measurement .
	?measurement dqv:isMeasurementOf <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/rules/creation/contributor/creation_contributor.ttl> ;
		dqv:computedOn  ?endpointDescription ;
		dqv:value ?v .
	OPTIONAL {
		# ID
		{ SELECT DISTINCT ?kg (AVG(xsd:decimal(?v)) AS ?valid ) WHERE {
			?kg prov:wasDerivedFrom ?kge ;
				dqv:hasQualityMeasurement ?measurement .
			?measurement dqv:isMeasurementOf <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/rules/creation/contributor/creation_contributorID.ttl> ;
				dqv:value ?v .
		} GROUP BY ?kg }
		# Type
		{ SELECT DISTINCT ?kg (AVG(xsd:decimal(?v)) AS ?valtype ) WHERE {
			?kg prov:wasDerivedFrom ?kge ;
				dqv:hasQualityMeasurement ?measurement .
			?measurement dqv:isMeasurementOf <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/rules/creation/contributor/creation_contributorType.ttl> ;
				dqv:value ?v .
		} GROUP BY ?kg }
		# Qualification
		{ SELECT DISTINCT ?kg (AVG(xsd:decimal(?v)) AS ?valqual ) WHERE {
			?kg prov:wasDerivedFrom ?kge ;
				dqv:hasQualityMeasurement ?measurement .
			?measurement dqv:isMeasurementOf <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/rules/creation/contributor/creation_contributorQualification.ttl> ;
				dqv:value ?v .
		} GROUP BY ?kg }
		# Influences
		{ SELECT DISTINCT ?kg (AVG(xsd:decimal(?v)) AS ?valinf ) WHERE {
			?kg prov:wasDerivedFrom ?kge ;
				dqv:hasQualityMeasurement ?measurement .
			?measurement dqv:isMeasurementOf <https://raw.githubusercontent.com/Jendersen/KG_accountability/main/rules/creation/contributor/creation_contributorInfluences.ttl> ;
				dqv:value ?v .
		} GROUP BY ?kg }
	}
	BIND( IF (BOUND(?valid) , ?valid, 0) AS ?vvalid)
	BIND( IF (BOUND(?valtype) , ?valtype, 0) AS ?vvaltype)
	BIND( IF (BOUND(?valqual) , ?valqual, 0) AS ?vvalqual)
	BIND( IF (BOUND(?valinf) , ?valinf, 0) AS ?vvalinf)
	BIND( (xsd:decimal(?v) + ?vvalid + ?vvaltype + ?vvalqual + ?vvalinf ) /5 AS ?val_contr )
}
